<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_recoveryCode</name>
   <tag></tag>
   <elementGuidId>57cca7b8-6a84-4c34-a6d0-1ccc21ce2b7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#account_tfa_code</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='account_tfa_code']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e1e10e40-ffad-4d79-b2b8-812a4c70e2cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>90c7c60d-2122-4b5e-b0fe-4acee3629707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tfa_code</value>
      <webElementGuid>04cbbdb9-dfba-4eac-a2f1-fef4f0a54652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6e7e9983-d939-47e2-87e7-9b2a21700e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autofocus</name>
      <type>Main</type>
      <value>autofocus</value>
      <webElementGuid>da5603a4-288b-4a62-ac06-bf9ba0bf5770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5662b712-6ba7-46bb-9396-80d8ed038e64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>000000000000</value>
      <webElementGuid>7e81d7ef-3ccd-4b36-a1d3-1a9cb3a41c8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>next-input</value>
      <webElementGuid>fc42b385-63bf-4715-89b1-b2e78cb21e41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>c1299849-b948-43cb-b560-a4fadabca807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a0c59928-2b8e-42e3-8644-9f060823eb2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>account_tfa_code</value>
      <webElementGuid>0a29ef36-a0cd-4eb8-84b9-c147f7e79125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;account_tfa_code&quot;)</value>
      <webElementGuid>29530f6f-8b5a-47d6-922c-671b5005cf42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='account_tfa_code']</value>
      <webElementGuid>24ea4783-848b-46a9-b33b-4366c881ac0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='body-content']/div[2]/div/div[2]/div/div/div[2]/div/div/form/div/div/input</value>
      <webElementGuid>f76fa275-4f56-4d22-96b3-dccacddd929b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>173f75b6-8137-4a7b-9449-2182e316c85b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'tfa_code' and @placeholder = '000000000000' and @type = 'text' and @id = 'account_tfa_code']</value>
      <webElementGuid>5d3bd99c-d0e4-4d62-9f6b-2a29e45ffe99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
