<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_store_name</name>
   <tag></tag>
   <elementGuidId>43afda20-3c0e-4a7f-804b-333d78139fa6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='Polaris-TextField']/child::input</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value></value>
      <webElementGuid>0574c197-4700-44c0-a2a8-e13b33ebbdda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
